import React, { Fragment } from 'react'

//third party
import { Container, Row, Col } from 'react-bootstrap'

//custom
import Authenticate from '../../components/Authenticate'
import Footer from '../../components/Layouts/Footer'
import Header from '../../components/Layouts/Header'
import { company_full } from '../../Helpers/statics'





const Revenue = () => {



    return (
        <Fragment>

            <title>Revenue Sharing Terms | {company_full}</title>
            <meta name="keywords" content="Revenue, Sharing, Terms, GripToons" />
            <meta name="description" content="Please read this Agreement, Privacy Policy and other applicable rules, policies, and terms posted on GripToons' Website or GripToon's App before using GripToon's Website, GripToons' App and Digital Content." />
            <meta property="og:title" content="GripToons' Revenue Sharing Terms" />
            <meta property="og:description" content="Please read this Agreement, Privacy Policy and other applicable rules, policies, and terms posted on GripToons' Website or GripToon's App before using GripToon's Website, GripToons' App and Digital Content." />
            <meta property="og:image" content="https://griptoons.com/img/bigRedBanner.jpg" />
            <meta property="og:url" content="https://griptoons.com/revenue_policy" />
            <meta name="twitter:card" content="summary_large_image" />
            <meta property="og:site_name" content="GripToons Entertainment" />
            <meta name="twitter:image:alt" content="GripToons Entertainment" />

            <Authenticate inside={true} strict={false} />
            <Header />


            <Container>

                <Row>

                    <Col md={1}></Col>

                    <Col md={10} className="legal pt-5 mt-5">

                        <h3>GRIPTOONS EARNINGS PROGRAM TERMS OF SERVICE</h3>

                        <p>
                            <strong>
                            THESE TERMS OF SERVICE ("TERMS") SET OUT BELOW GOVERN YOUR PARTICIPATION IN THE GRIPTOONS EARNINGS PROGRAM. PLEASE READ THESE TERMS CAREFULLY AS THEY CONTAIN IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, REMEDIES AND OBLIGATIONS.
                            </strong>
                        </p>

                        <p>
                        The GRIPTOONS EARNINGS PROGRAM (the "Program") which includes Payments made by users to read your series (the “Coin Earn”) and earnings you make from our Ad sharing Program (the “Ad Sharing Scheme”) is operated by GRIPTOONS ENTERTAINMENT Inc. (including its subsidiary, hereinafter together referred to as “GRIPTOONS” or “we”).
                        </p>

                        <p>
                            <strong>General</strong><br />
                            GRIPTOONS provides two types of income revenue in our Program, The Coin Earn program which involves users paying to view series/episodes that you monetize, and our Ad Sharing Scheme which involves creators voluntarily participating in our sharing of Ad Income based on the number of monthly views of series and/or episodes. The program provides a revenue stream to creators who (i) become a Creator in accordance with these Terms, and (ii) thereafter, elect to participate in either or both of our earnings programs. Specifically, upon applying and/or participation in the Program, the participating creators (“Members”) will receive a portion of the Net Ad Revenue and/or Coin Usage Revenue, defined below, generated by GRIPTOONS as set forth in these terms.
                        </p>

                        <p>
                        Only those creators who become Members in either of the Earning Programs in accordance with these Terms defined below will be entitled to share in any form of Revenue.
                        </p>

                        <p>
                        THERE IS NO GUARANTEE THAT MEMBERS OF THE AD SHARING SCHEME WILL RECEIVE ANY EARNINGS AS A RESULT OF THEIR PARTICIPATION IN THIS PARTICULAR PROGRAM.
                        </p>


                        <p>
                        These Terms, together with the Terms of Use, Privacy Policy, Community Policy and Uploading Guidelines and other applicable policies and terms of GRIPTOONS constitute the entire agreement by and between, GRIPTOONS and you (the "Agreement"). (For purposes of the Agreement and these Terms, "you" means the individual or entity using the Service and/or applying to participate in the Program and/or any individual, agent, employee, representative, network, parent, subsidiary, affiliate, successor, related entities, assigns, or all other individuals or entities acting on your behalf, at your direction, under your control, or under the direction or control of the same individual or entity who controls you). Capitalized terms not defined in these Terms are defined elsewhere in the Agreement.
                        </p>

                        <p>
                        By participating in the Program, you agree to be bound by the Agreement, including these Terms. GRIPTOONS reserve the right to modify or amend these Terms and/or the Agreement at any time by publishing an amended version on the GRIPTOONS Website and/or the GRIPTOONS App. Although GRIPTOONS will try to notify you when major changes are made to the Agreement and/or these Terms, you should periodically review the most up-to-date version thereof, as you will be bound by the terms of the most current form of the Agreement and these Terms. Changes to the Agreement and/or these Terms will generally become effective 30 days after they are posted. However, changes addressing new functions for the Program or changes made for legal reasons may be effective immediately. If you do not agree to any modifications or amendments to these Terms and/or the Agreement, your sole recourse is to immediately cancel your membership in the Program, as provided at your dashboard, and to cease using the Service.

                        </p>

                        <p>
                        Please read these Terms and the Agreement carefully. Your participation in the Program is only as permitted by these Terms and any applicable laws.
                        </p>


                        <ol>
                            
                            <li>
                                <p>
                                    <strong>Joining the Program</strong><br />
                                    You are eligible to join the coin earn program once you (i) have at least one or more episodes in any series on your GRIPTOONS account, (ii) are the older of (A) 18 years of age, or (B) of legal age or capacity to form a binding contract under the laws of the country in which you are resident or from which you intend to access and/or use the Services, and (iii) agree to these Terms.
                                </p>

                                <p>
                                You are allowed to join either or both of the current Programs we provide (Coin Earn &amp; Ad Sharing Scheme).
                                </p>

                                <p>
                                In furtherance of the foregoing, you represent to us that you are at least 18 years of age or of legal age or capacity to form a binding contract under the laws of the country in which you are resident or from which you intend to access and/or use the Services. We may terminate your participation in the Program if it comes to our attention that you are under 18 years old and/or not of legal age or capacity to form a binding contract under the laws of the country in which you are resident or from which you intend to access and/or use the Services. GRIPTOONS is not responsible for any consequences, financial or otherwise, arising from or in any way related to your participating in the Program if you are under 18 years old or are not of legal age or capacity to form a binding contract under the laws of the country in which you are resident or from which you intend to access and/or use the Services.
                                </p>

                                <p>
                                If you are applying to participate in the Program on behalf of a business or entity, you represent and warrant that you have the full legal authority to bind the business or entity to the Agreement and these Terms and further agree to indemnify and hold GRIPTOONS, together with their respective officers, directors, owners, partners, agents, and employees, harmless from and against any and all claims, losses, damages, judgments, suits, actions, and/or costs and expenses, including, without limitation, attorney fees and costs, arising from or related to use of the Service by such business or entity, violation of the Agreement and/or these Terms by such business or entity, and/or participation in the Program by such business or entity.
                                </p>

                                <ol type="A">
                                    <li>
                                        <strong>Joining the Coin Earn Program</strong><br />
                                        In order to participate in the Program, you must toggle on the “Monetize” feature on the episode that you wish to monetize (Monetizing your episode means you are requesting that users pay a token of 1 coin to have access to view your episode. These coins are purchased by the users on GRIPTOONS as a means of gaining access to any episode that has been monetized)
                                    </li>

                                    <li>
                                        <strong>Joining the Ad Sharing Scheme</strong><br />
                                        In order to be a member of the Ad Sharing Scheme, you must apply to have your series approved for the Ad Sharing Scheme. Approval by GRIPTOONS of your participation in the Program does not guarantee that you will receive any Net Ad Revenue. <br /><br />
                                        For minimum requirements for the Ad Sharing Scheme, please refer to Paragraph 3 below:
                                    </li>
                                </ol>

                            </li>


                            <li>
                                <p>
                                    <strong>Opting out of the Program</strong><br />

                                    <ul>
                                        <li>
                                        You may opt out of either of the program any time
                                        </li>

                                        <li>
                                        You can opt out of the “Coin Earn” program for any episode by toggling off the Monetize feature on that particular episode. (Coin Earn Program is activated per episode)
                                        </li>

                                        <li>
                                        You can opt out of the “Ad Sharing Scheme” by revoking your membership in the program.
                                        </li>

                                        <li>
                                        If you decide to opt-out of the Ad Sharing Scheme or are removed from the Program by GRIPTOONS, you may be eligible to rejoin the Program upon (i) reapplying to GRIPTOONS to become a Member of the Program, and (ii) being approved by GRIPTOONS, in its sole discretion, (iii) as well as satisfying any conditions then required by GRIPTOONS, provided, however, that in no event may you reapply to participate in the Program for (2) months following the date upon which you opted-out or were removed from the Program.
                                        </li>
                                    </ul>
                                </p>
                            </li>


                            <li>
                                <p>
                                    <strong>Eligibility</strong><br />

                                    <ol type="A">
                                        <li>
                                            <strong>Coin Earn Program</strong><br />
                                            Any episode is eligible for the Coin Earn Program as long as that episode and/or series does not violate any of our guidelines and/or Terms.
                                        </li>

                                        <li>
                                            <strong>Ad Sharing Scheme</strong><br />
                                            Your series is eligible to apply for this program after the series satisfies all the requirements below:<br />

                                            <ul>
                                                <li>
                                                A minimum of 1,000 subscribers to that series.
                                                </li>
                                            </ul>
                                        </li>
                                    </ol>
                                </p>
                            </li>


                            <li>
                                <p>
                                    <strong>Legal Rights/Ownership</strong><br />

                                    <ul>
                                        <li>
                                            <strong>Users who upload content are solely responsible for compliance with all applicable laws, including, without limitation, all copyright laws. By accepting these Terms, you hereby agree to indemnify and hold GRIPTOONS, together with their respective officers, directors, owners, subsidiaries, affiliates, partners, agents, and employees harmless from and against any and all claims, damages, costs and expenses in any way related to or arising from your content, including, without limitation, violation of any applicable copyright laws.</strong>
                                        </li>

                                        <li>
                                            <strong>If two or more creators have worked on a Series, the creator who uploaded the Series hereby agrees to distribute all Net Revenue, if any, to the other creators ("Other Creators") in accordance with the agreement between you and the Other Creators. GRIPTOONS hereby disclaim any and all responsibility for payment to the Other Creators. GRIPTOONS further disclaim any and all responsibility for violation of copyright or other laws by the creators. The creators, including you and the Other Creators, jointly and severally, shall be liable for any and all matters related to the Series, including, without limitation, any copyright infringement.</strong>
                                        </li>
                                    </ul>
                                </p>
                            </li>


                            <li>
                                <p>
                                    <strong>Revenue Numbers</strong><br />
                                    <strong>Note:</strong> The numbers displayed here are for reference purposes only. These numbers may or may not play out in the total revenue you earn on your series.<br />

                                    <ol type="A">

                                        <li>
                                            <strong>Coin Earn</strong><br />
                                            <ul>
                                                <li>
                                                The average revenue per coin spent on your series by readers is <strong>NGN 10.00</strong>
                                                </li>
                                            </ul>
                                        </li>

                                        <li>
                                            <strong>Ad Sharing Scheme</strong><br />

                                            <ul>
                                                <li>
                                                The average revenue per view of your series by readers is <strong>NGN 5.00</strong> 
                                                </li>

                                                <li>
                                                Your Ad Sharing Revenue on a monthly basis remains invalid until you have at least 3,000 views. For example : If at the end of the month (when your revenue is calculated) you have 2,500 views for your series (and are approved to receive Ad Sharing Revenue), all your views will amount to  N0.00 for that particular series. But if you have 3,100 views for your series, you will receive the value for 3,100 views since you are above the threshold of validity. Every new month your valid counts reverts to zero, views are not carried over to the next month.
                                                </li>
                                            </ul>
                                        </li>

                                    </ol>
                                </p>
                            </li>


                            <li>
                                <p>
                                    <strong>GRIPTOONS’ Right to Refuse Payment</strong><br />
                                    You will not be entitled to any Revenue in your Account if the Series or your use of the Service materially violates the Agreement and/or the Terms, which violations may include, without limitation, the following:<br />

                                    <ul>
                                        <li>
                                        our Series or any of your content is in violation of the Community Policy and Uploading Guidelines;
                                        </li>

                                        <li>
                                        Third parties claim rights regarding the Series and/or any of your content, including, without limitation, copyright claims;
                                        </li>

                                        <li>
                                        Your membership in the Program is suspended or cancelled.
                                        </li>
                                    </ul>
                                </p>
                            </li>


                            <li>
                                <p>
                                    <strong>Payment</strong><br />

                                </p>

                                <p>
                                    7.1. &emsp; <strong>Payment Conditions</strong><br />
                                    You are only entitled to payment of Net Revenue if the balance in your Account wallet is a multiple of NGN 10,000. For example, if the balance in your Account is NGN 3,800 ; you won’t be paid out for the month, instead, that amount will be rolled over to the next month's revenue. If your balance is NGN 12,500; you would be paid NGN 10,000 and the NGN 2,500 balance will be rolled over to the next month’s revenue.
                                </p>

                                <p>
                                    7.2. &emsp; <strong>Payment Schedule</strong><br />
                                    Your account wallet/account will update on the last day of each month (for that current month’s revenue) and display on your payments table of your creator Dashboard. You will not receive a separate email notification regarding payment updates. Provided you are in compliance with the Agreement and these Terms, and your current balance in your Account meets the minimum threshold amount of NGN 10,000, you will receive payment <strong>no later than the 7th day</strong> of the following month, provided, however, that GRIPTOONS reserves the right to delay payment in the event we suspect you have violated the Agreement and/or these Terms.
                                </p>

                                <p>
                                    7.4. &emsp; <strong>Payment Requirements</strong><br />
                                    In order to receive payment, you must register with and maintain a valid Nigerian Bank Account. Banking details can be registered on the options page of your account. GRIPTOONS is not responsible for any payment error, including any unpaid Net Revenue amount, if such error is a result of an incorrect Banking information.
                                </p>

                                <p>
                                    7.5. &emsp; <strong>Payment Example</strong><br />
                                    Let’s say you had an existing wallet balance of NGN1,500 as of May 1<br />

                                    <ul>
                                        <li>
                                        If you earn NGN 3,000 of Net Revenue during the month of May, the amount will appear on your wallet by May 31st. Your total balance would be NGN4,500 (previous balance of NGN1,500 + your May Neet Revenue share of NGN3,000). However, no payments would be made out to you as your balance would be below the minimum threshold amount of NGN10,000. The balance of NGN4,500 would carry over to the following month.
                                        </li>

                                        <li>
                                        If you earn NGN24,000 during the month of May, your total balance would be NGN25,500 (previous balance of NGN1,500 + your May Net Revenue share of NGN24,000). We would pay you NGN 20,000 for the month of June. Your Account will have a remaining balance of NGN 5,500, which will be carried over to the next month.
                                        </li>
                                    </ul>
                                </p>

                                <p>
                                    7.6. &emsp; <strong>Taxes</strong><br />
                                    <strong>
                                    You are solely responsible for the payment of all taxes (if any) associated with your participation in the Program, including your receipt of any Net Revenue, as well as the preparation and timely filing of all documentation required by taxing authorities having jurisdiction over you and/or your activities. 
                                    </strong>
                                </p>
                            </li>


                            <li>
                                <p>
                                    <strong>Usage REstrictions</strong><br />
                                    <strong>
                                    GRIPTOONS may periodically check whether your content or your use of the Service violates the Agreement and/or these Terms. Please read the following carefully so that you can enjoy the Service and participate in the Program without any restrictions.
                                    </strong><br /><br />

                                    Causes for Restricting or Terminating Usage of the Service and/or Participation in the Program<br />
                                </p>

                                <p>
                                    8.1 &emsp; <strong>Prohibited Actions</strong><br />
                                    The following actions are prohibited under any circumstances:<br />

                                    <ul>
                                        <li>
                                        Continuously and repeatedly reading and/or liking episodes or series, whether manually or using tools such as macro programs;
                                        </li>

                                        <li>
                                        Altering or modifying information collected by or provided to GRIPTOONS for operating the Service and/or the Program;
                                        </li>

                                        <li>
                                        Failing to comply with the Agreement and/or these Terms;
                                        </li>

                                        <li>
                                        Otherwise adversely affecting the operation of the Service and/or the Program by any illegal or harmful means; and/or
                                        </li>

                                        <li>
                                        Invalid Clicks, discussed at Section 8.2below.
                                        </li>
                                    </ul>
                                </p>

                                <p>
                                    8.2. &emsp; <strong>Invalid Clicks and Actions which Induce Them</strong><br />
                                    Clicks on any Ad Display are assumed to be based on the interest of visitors to the Service. Repeated clicks and ‘clickbait’ phrases created by macro programs or individual users are considered ‘invalid clicks’ ("Invalid Clicks"). GRIPTOONS strictly prohibits generating or inducing Invalid Clicks by any means whatsoever, including, without limitation, as follows:<br />

                                    <ul>
                                        <li>
                                        Continuously and repeatedly clicking Ad Displays;
                                        </li>

                                        <li>
                                        Incorporating phrases, figures, images, etc. in your content which induce visitors to click Ad Displays, such as "Click this ad", "Please help", "Click the link", etc.;
                                        </li>

                                        <li>
                                        Using email, messenger, text messaging, etc. to send messages requesting clicks; and/or
                                        </li>

                                        <li>
                                        Using robots, automated click and exposure-generating tools, automatic web browsing, click exchange programs, or any other means to artificially generate clicks.
                                        </li>
                                    </ul>
                                </p>


                                <p>
                                    8.3. &emsp; <strong>Transferring Accounts</strong><br />
                                    You may not, and agree not to, share, transfer, sell or resell your Account.
                                </p>

                                <p>
                                    8.4. &emsp; <strong>Publishing Inappropriate Content</strong><br />
                                    You may not, and agree not to, publish content which violates the Agreement and/or the Terms. GRIPTOONS periodically reviews your content for compliance with the Agreement and the Terms and in the event that GRIPTOONS determines that any of your content, including any Approved Series, is in violation of the Agreement and/or the Terms, your Account and/or access to the Service and/or the Program may be suspended or terminated, as determined by GRIPTOONS in its sole discretion.
The standards for content can be found in the Community Policy and Uploading Guidelines
                                </p>

                                <p>
                                    8.5. &emsp; <br />
                                    <strong>Note: </strong> You must mark your series as "Adult Content" if it contains any mature subject matter or explicit content, provided, however, that all content must meet the Community Policy and Uploading Guidelines whether or not your series is marked as "Adult Content".<br /><br />
                                    <strong>Note: </strong> If you violate copyright law or otherwise infringe on the rights of any third party, your content will be removed by GRIPTOONS, your use of the Service and your participation in the Program will be suspended or terminated immediately, and you will forfeit any Net Revenue payment you may have earned.
                                </p>

                                <p>
                                    8.6. &emsp; <strong>Malicious Actions Against Other Users</strong><br />
                                    You agree not to take any malicious, abusive, threatening or demeaning action against other users of the Service and the GRIPTOONS community. By way of example only, "malicious action" might include destructive criticism, cursing, stalking, impersonation, or invasion of privacy in any form or by any method. In the event GRIPTOONS determines that you have engaged in any such malicious action, GRIPTOONS reserves the right to terminate your participation in the Program, suspend or terminate your Account, and terminate your right to use the Service.
                                </p>
                            </li>


                            <li>
                                <p>
                                    <strong>Representations; Warranties</strong><br />
                                    You represent and warrant that (i) you have full power and authority to enter into the Agreement and these Terms; (ii) you are the owner of, or are legally authorized to act on behalf of the owner of, all series/content uploaded by you onto the Service and for which you seek Revenue; (iii) you are the technical and editorial decision maker in relation to and have full control over to all content on which you seek Revenue; (iv) GRIPTOONS has never previously terminated or otherwise disabled a Revenue Sharing Account created for by you for any reason; (v) entering into the Agreement and/or these Terms, becoming a Member of the Program will not violate any agreement you have with a third party or any third-party rights; and (vi) all of the information provided by you to GRIPTOONS is true, correct and current.
                                </p>
                            </li>


                            <li>
                                <p>
                                    <strong>No Warranties</strong><br />
                                    <strong>
                                    OTHER THAN AS EXPRESSLY SET OUT IN THESE TERMS, GRIPTOONS MAKE NO PROMISES ABOUT THE SERVICES, THE PROGRAM AND/OR REVENUE. FURTHERMORE, GRIPTOONS MAKE NO GUARANTEE THAT ANY OF YOUR CONTENT WILL RECEIVE REVENUE, EVEN IF YOUR REQUESTED SERIES FOR AD SHARING REVENUE IS APPROVED BY GRIPTOONS. ADDITIONALLY, GRIPTOONS MAKE NO ANY COMMITMENTS ABOUT THE FUNCTIONALITY AND/OR CONTENT WITHIN THE SERVICE, THE PROGRAM AND/OR ANY REVENUE PROGRAM, OR THE PROFITABILITY, RELIABILITY, AVAILABILITY, OR ABILITY TO MEET YOUR NEEDS AND/OR EXPECTATIONS OF THE SERVICE, THE PROGRAM AND/OR AD DISPLAY.<br /><br />
                                    </strong>

                                    <strong>
                                    NOTHING IN THE AGREEMENT OR THESE TERMS SHALL EXCLUDE OR LIMIT GRIPTOONS’S WARRANTY OR LIABILITY FOR LOSSES WHICH MAY NOT BE LAWFULLY EXCLUDED OR LIMITED BY APPLICABLE LAW. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR CONDITIONS OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR LOSS OR DAMAGE CAUSED BY NEGLIGENCE, BREACH OF CONTRACT OR BREACH OF IMPLIED TERMS, OR INCIDENTAL OR CONSEQUENTIAL DAMAGES.<br /><br />
                                    </strong>

                                    <strong>
                                    ACCORDINGLY, ONLY THE LIMITATIONS WHICH ARE LAWFUL IN YOUR JURISDICTION WILL APPLY TO YOU AND GRIPTOONS’S LIABILITY WILL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW. YOU EXPRESSLY UNDERSTAND AND AGREE THAT YOUR ACCESS TO THE SERVICE AND YOUR PARTICIPATION IN THE PROGRAM IS AT YOUR SOLE RISK AND THAT THE SERVICES AND PROGRAM, AS WELL AS ANY AD DISPLAY, ARE PROVIDED "AS IS" AND "AS AVAILABLE." IN PARTICULAR, NEITHER GRIPTOONS, NOR ANY OF THEIR SUBSIDIARIES, AFFILIATES, SERVICE PROVIDERS AND/OR ADVERTISERS REPRESENT OR WARRANT TO YOU THAT: (I) YOUR USE OF THE SERVICES AND/OR YOUR PARTICIPATION IN THE PROGRAM, INCLUDING ANY REVENUE SHARING SCHEME, WILL MEET YOUR REQUIREMENTS AND/OR YOUR EXPECTATIONS, (II) YOUR USE OF THE SERVICES, YOUR PARTICIPATION IN THE PROGRAM AND/OR ANY REVENUE EARNED WILL BE UNINTERRUPTED, TIMELY, SECURE OR FREE FROM ERROR, (III) ANY INFORMATION OBTAINED BY YOU AS A RESULT OF YOUR USE OF THE SERVICES AND/OR YOUR PARTICIPATION IN THE PROGRAM WILL BE ACCURATE OR RELIABLE, AND/OR (D) THAT DEFECTS IN THE OPERATION OR FUNCTIONALITY OF THE SERVICES, THE PROGRAM AND/OR ANY REVENUE EARNED WILL BE CORRECTED. ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICES AND/OR PARTICIPATION IN THE PROGRAM IS DONE AT YOUR OWN DISCRETION AND RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR OTHER DEVICE OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM GRIPTOONS OR THROUGH OR FROM THE SERVICES AND/OR THE PROGRAM SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE TERMS. GRIPTOONS FURTHER EXPRESSLY DISCLAIM ALL WARRANTIES AND CONDITIONS OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
                                    </strong>
                                </p>
                            </li>


                            <li>
                                <p>
                                    <strong>Extent of Liability</strong><br />

                                    <strong>
                                    TO THE EXTENT PERMITTED BY LAW, (i) YOU EXPRESSLY UNDERSTAND AND AGREE THAT NEITHER GRIPTOONS, NOR ANY OF THEIR SUBSIDIARIES AND AFFILIATES, OR SUPPLIERS AND LICENSORS SHALL BE LIABLE TO YOU FOR: (I) ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES WHICH MAY BE INCURRED BY YOU, HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY. THIS SHALL INCLUDE, BUT NOT BE LIMITED TO, ANY LOSS OF PROFIT (WHETHER INCURRED DIRECTLY OR INDIRECTLY), ANY LOSS OF GOODWILL OR BUSINESS REPUTATION, ANY LOSS OF DATA SUFFERED, COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, OR OTHER INTANGIBLE LOSS; (II) ANY LOSS OR DAMAGE WHICH MAY BE INCURRED BY YOU, INCLUDING BUT NOT LIMITED TO LOSS OR DAMAGE AS A RESULT OF: (A) ANY CHANGES WHICH WE MAY MAKE TO THE SERVICES AND/OR PROGRAM, OR FOR ANY PERMANENT OR TEMPORARY CESSATION IN THE PROVISION OF THE SERVICES AND/OR PROGRAM (OR ANY FEATURES WITHIN THE SERVICES AND/OR PROGRAM); (B) THE DELETION OF, CORRUPTION OF, OR FAILURE TO STORE, ANY CONTENT AND OTHER COMMUNICATIONS DATA MAINTAINED OR TRANSMITTED BY OR THROUGH YOUR USE OF THE SERVICES AND/OR PARTICIPATION IN THE PROGRAM; (C) YOUR FAILURE TO PROVIDE US WITH ACCURATE ACCOUNT INFORMATION; (D) YOUR FAILURE TO KEEP YOUR PASSWORD OR ACCOUNT DETAILS SECURE AND CONFIDENTIAL. THE LIMITATIONS ON OUR LIABILITY ABOVE SHALL APPLY WHETHER OR NOT WE HAVE BEEN ADVISED OF OR SHOULD HAVE BEEN AWARE OF THE POSSIBILITY OF ANY SUCH LOSSES ARISING.<br /><br />
                                    </strong>

                                    <strong>
                                    FOR CLARITY, IN NO EVENT SHALL GRIPTOONS AND/OR ANY OF ITS AFFILIATES OR SUBSIDIARIES BE LIABLE TO YOU UNDER THESE TERMS OR OTHERWISE FOR ANY CONSEQUENTIAL, SPECIAL, INDIRECT, EXEMPLARY, OR PUNITIVE DAMAGES WHETHER IN CONTRACT, TORT, OR ANY OTHER THEORY, EVEN IF YOU HAVE OR HAVE NOT BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY, AND (ii) TO THE EXTENT GRIPTOONS ARE DETERMINED TO HAVE ANY LIABILITY TO YOU NOTWITHSTANDING THE EXPRESS WAIVER AND RELEASED CONTAINED IN THESE TERMS, GRIPTOONS’, TOGETHER WITH THEIR AFFILIATES AND SUBSIDIARIES, AGGREGATE LIABILITY UNDER THESE TERMS IS LIMITED TO THE NET AMOUNT RECEIVED AND RETAINED BY YOU IN CONNECTION WITH THESE TERMS DURING THE THREE MONTH PERIOD IMMEDIATELY PRECEDING THE DATE OF THE CLAIM. NOTWITHSTANDING AND WITHOUT LIMITATION OF THE FOREGOING, IN ALL CASES, GRIPTOONS, TOGETHER WITH THEIR AFFILIATES AND SUBSIDIARIES, WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE THAT IS NOT REASONABLY FORESEEABLE. EACH PARTY ACKNOWLEDGES THAT THE OTHER PARTY HAS ENTERED INTO THESE TERMS RELYING ON THE LIMITATIONS OF LIABILITY STATED HEREIN AND THAT THOSE LIMITATIONS ARE AN ESSENTIAL BASIS OF THE BARGAIN BETWEEN THE PARTIES.
                                    </strong>
                                </p>
                            </li>


                            <li>
                                <p>
                                    <strong>Indemnification</strong><br />

                                    <strong>
                                    You hereby agree to indemnify and defend GRIPTOONS, together with their affiliates, subsidiaries, owners, officers, directors, agents, employees and advertisers from and against any and all third-party claims and liabilities arising out of or related to your content, your use of the Services, your participation in the Program, the placement of Ad Display in any of your content, including any Approved or Non-approved Series, and/or your breach of any term of the Agreement and/or the Terms. BE ADVISED THAT GRIPTOONS’ ADVERTISERS ARE THIRD PARTY BENEFICIARIES OF YOUR INDEMNIFICATION ABOVE.
                                    </strong>
                                </p>
                            </li>


                            <li>
                                <p>
                                    <strong>Privacy</strong><br />
                                    By using the Service and/or joining the Program, you agree that GRIPTOONS can use your personal data in accordance with our privacy policy.
                                </p>
                            </li>

                            <li>
                                <p>
                                    <strong>Independent Contractor</strong><br />
                                    Your relationship with GRIPTOONS is that of an independent contractor and neither your participation in the Program nor the Terms nor the Agreement create any agency, partnership, or joint venture.
                                </p>
                            </li>


                            <li>
                                <p>
                                    <strong>Miscellaneous Provisions</strong>
                                </p>

                                <p>
                                The Agreement, including these Terms, sets forth all (and is intended by all parties to be an integration of all) of the representations, promises, agreements and understandings among you, GRIPTOONS, and supersedes any and all prior or contemporaneous oral or written communications and/or agreements between you and GRIPTOONS, all of which are merged herein. These Terms may be amended (i) in a writing wet signed by both parties that expressly states that it is amending these Terms, or (ii) as set forth above, if you keep using the Services after GRIPTOONS modifies the Terms.
                                </p>

                                <p>
                                You may not assign or transfer any of your rights as a Member of the Program and/or under these Terms. GRIPTOONS, however, may assign its rights.
                                </p>

                                <p>
                                The headings of the articles and sections of these Terms are inserted for convenience only and shall not be deemed to be a part of these Terms.
                                </p>

                                <p>
                                No amendment, change or modification of these Terms shall be valid unless posted on this Website by GRIPTOONS or otherwise agreed to in writing and wet signed by both GRIPTOONS and you.
                                </p>

                                <p>
                                If you do not comply with these terms, and GRIPTOONS does not take action right away, such inaction does not mean that GRIPTOONS are giving up any rights that either may have, including taking action in the future.
                                </p>

                                <p>
                                If any provision of these Terms is determined by any court or arbitrator of competent jurisdiction to be invalid, illegal or unenforceable in any respect, such provision will be enforced to the maximum extent possible given the intent of the parties hereto. If such clause or provision cannot be so enforced, such provision shall be stricken from these Terms and the remainder of these Terms will be enforced as if such invalid, illegal or unenforceable clause or provision had (to the extent not enforceable) never been contained in this Agreement.
                                </p>

                                <p>
                                These Terms control the relationship between GRIPTOONS and you. They do not create any third party beneficiary rights, other than as expressly set forth in these Terms.
                                </p>

                                <p>
                                Neither party will be liable for inadequate performance to the extent caused by a condition (for example, natural disaster, act of war or terrorism, riot, labor condition, governmental action, and Internet disturbance) that was beyond the party's reasonable control.
                                </p>

                                <p>
                                In connection with your use of the Services and/or participation the Program, we may contact you regarding service announcements, administrative messages, and other information.
                                </p>
                            </li>

                        </ol>

                        

                    </Col>

                </Row>

            </Container>

            <Footer />

        </Fragment>
    )
}



export default Revenue